export default {
  pages: [
    'pages/login/index',
    'pages/index/index',
    'pages/group/index',
    'pages/member/index',
    'pages/notifications/index',
    'pages/mine/index',
    'pages/subscribe/index',
    'pages/payment/index',
    'pages/success/index',
    'pages/member-code/index',
    'pages/benefits/index',
    'pages/benefit-detail/index',
    'pages/points/index',
    'pages/renewal/index',
    'pages/group-qr/index',
    'pages/advisor/index',
    'pages/message/index',
    'pages/invite/index',
    'pages/invite-poster/index',
    'pages/training/index',
    'pages/courses/index',
    'pages/course/index',
    'pages/courseware/index',
    'pages/diagnosis/index',
    'pages/diagnosis-booking/index',
    'pages/booking-result/index',
    'pages/ticket/index',
    'pages/ticket-result/index',
    'pages/review/index',
    'pages/refund/index',
    'pages/refund-result/index',
    'pages/tasks/index',
    'pages/earnings/index',
    'pages/agent/index',
    'pages/settings/index',
    'pages/agreement/index',
    'pages/scan-login/index',
  ],
  window: {
    navigationStyle: 'custom',
    backgroundTextStyle: 'dark',
    backgroundColor: '#FFF7EC',
    navigationBarBackgroundColor: '#FFF7EC',
    navigationBarTitleText: '主理人公社',
    navigationBarTextStyle: 'black',
    enablePullDownRefresh: false,
  },
  style: 'v2',
  lazyCodeLoading: 'requiredComponents',
  __usePrivacyCheck__: true,
  sitemapLocation: 'sitemap.json',
}
